language: python

python:
  - '2.7'
  
sudo: false

cache:
  directories:
    - ~/.platformio
env:
  - PLATFORMIO_CI_SRC=src/

install:
  - pip install -U platformio

script:
  - platformio run -e esp12e_dev

deploy:
  on:
    repo: jaredbebb/aws-iot-pump
    all_branches: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
  skip_cleanup: true
  provider: releases
  overwrite: true
  api_key:
    secure: ypC157aJ3Z16ildGTgM7ClnQO5UAu926n5fdNu8nEDwZLfB2LAFV1DgD7ZwKvmLrahuC5KBulfpIgZypNnK8Lenu2GtKJMJTQeOd9abcbqyBvt1xXuJd6sEBY4EEXYdYkc1z2Viuqs679AyAjFmI2edt7Gos+ZfX3pqfItgV9fU0Di3QAyj9QkvZgrkoQ61GFzyy1j142aAO/EplXKcUUbDwGcnYrTNBaoeeb6PxcYUi6pvZKBAVoFqZXxneP427S8YHwaRg0RKQBeKZ7Y+BePgvGvUbNEF3aOROLFi7R7TiuTm30X8BqW7xoBjQXv8W86D5dM3NQFI/Qj3W0LRwucOxrBY+v4TP1Pt2sOoOVmBLOLGZ/On2OAryfJS679/f5fZVaq73NWiPcAwX3QsGt+pxHhgrhxwvkFHL7wYrHcrwgiuXBtjmQwnQCrECVZuirwTMdYViXlXpANJjvIfd1TV5/iXbw1FrBEMGNR4VVWyOwU8oVaDBlC7kSQfuLJ4AwJHG0p++N8BMtKSxtkZTMih7f4C4r7Tp/aAtxzL0vWyWGSN+a7gAuVL7ujcIsTUWdOJmFCALoDokohQ2ijrUGK1LaXIhO7buEuakFX0zg7/jujV4qXrOMJyDtS42+hBZNpTV1IIRV13oXiH5LTBmfj5ON3C8eGYjxLlFZaaLRXQ=
  file: ".pio/build/esp12e_dev/firmware.bin"