language: python

python:
  - '2.7'
  
sudo: false

cache:
  directories:
    - ~/.platformio
env:
  - PLATFORMIO_CI_SRC=src/

install:
  - pip install -U platformio

script:
  - platformio run -e esp12e_dev

deploy:
  on:
    repo: jaredbebb/aws-iot-pump
    all_branches: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
  skip_cleanup: true
  provider: releases
  overwrite: true
  api_key:
    secure: AdOxGvSE/dtwjDyaab2Sgtd/13ix0UzhlBtw4e+Zgu+5ZNCODEkxpi7rHRmla6GUmFRmqbDeLZLgdShO5kgrDdRBgSPkT2EuQ4kLLdFpF2qCEhpyJyTmT5FwPHbQtFXGmFfACU0MtUyDtlpKEmGr0fdKLjw+VQ4wvXQPdAYESVXzWbVhqi7unQJhgLweDkZeWmX8oXNFplTEh10GIk9HL7jjmt4gmL4H3WIBTOKurFYJZ9KXp3wDorQ4UuEKHrTefBT9HDZG9adoiQo9NAmvD/BS0HWbbwhNaSnmN+Af+kqLF+ZCEBVSiCnof/gZcevcmbIwPC5h/qGQLCNx0UAA5ruc4WjnWsb5WiemLt4j/yozYYNkYLpL5oRoB6aKqsTrotfDQGK1DjGmh3x1hx+zUmQvZvQ+45Kh7Uoz1cE8Q8fMHMCa0IFjSZzB2dierm/ydDWQdcvLVcSpTQwKzu1jcU3lpa1viF6MhYDInzkRpZwMOhNvafSv9KkKbNB/bFb+vcQZMVYi+YbAQL4cHaaD2PWNu1jxrsSJ0D1BwAEhFbQRgaNQtLs0U63PTc443oUuRedv4AQd/pWN93sjcS9SuUWYhzFaLpU4VCA+jv701CW6NX3iUxhhIPmv7lci5hEfmA9lT3rago2jEbhLz5hl3NZoAYPuPci9v2BvW3FipW4=
  file: ".pio/build/esp12e_dev/firmware.bin"